### ISSUE TITLE
Usage and installation instructions

### ISSUE THREAD

**Issue by wigging** [rodolfo-enq/gasification#1]
The README doesn't describe how to install and run this code. Please update the README with usage and installation instructions.

**Comment by rodolfo-enq** [comment]
Gavin,

Thanks for your interest in my code.

You don't need to install it. Just copy the files and run the scripts. 

This code is a library of functions for better use of Cantera for biomass and coal cogasification using equillibrium calculations. The main functions are: [coprocessing](https://github.com/rodolfo-enq/gasification/blob/fdb232a03e93cd6a640ebc2bf53f266a00b80f31/gasifier.py#L902) and [coprocessing1](https://github.com/rodolfo-enq/gasification/blob/fdb232a03e93cd6a640ebc2bf53f266a00b80f31/gasifier.py#L1069). The usage instructions are available at the function definitions themself. There are 2 samples for use of this functions: [test_chap4_fig4_1.py](https://github.com/rodolfo-enq/gasification/blob/fdb232a03e93cd6a640ebc2bf53f266a00b80f31/test_chap4_fig4_1.py) and [test_chap4_fig4_2.py](https://github.com/rodolfo-enq/gasification/blob/fdb232a03e93cd6a640ebc2bf53f266a00b80f31/test_chap4_fig4_2.py).

There is currently a student working to update this code. I hope to have updates soon.

Rodolfo

**Comment by wigging** [comment]
What you said in your previous comment should be in the README.
